### ISSUE TITLE
Unpaired RNA and ATAC

### ISSUE THREAD

**Issue by SITRR** [welch-lab/MultiVelo#39]
Hello,

Thank you very much for your package! I was wondering if you had a vignette for unpaired RNA and ATAC analysis. 

Best,
Susana

**Comment by danielee0707** [comment]
Hi, unfortunately, MulitVelo currently only works on paired RNA-ATAC multi-omic samples, which is also our recommendation. There are algorithms that attempt to match scRNA and scATAC cells through expression/accessibility similarity, but by doing so, the interesting decoupling information between modalities that MultiVelo is specifically designed to reveal would be lost.

**Comment by SITRR** [comment]
@danielee0707 that’s a shame. Thank you for getting back to me though! 

Best,
Susana

**Comment by jw156605** [comment]
To be clear: MultiVelo requires paired RNA and ATAC measurements as input. However, we showed in the paper that MultiVelo can still produce reasonable results in some cases if the paired measurements are computationally inferred rather than experimentally measured. But we didn't provide a tutorial about how to do this because we expect MultiVelo to be most useful for true paired measurements.
**********************************************************
Electronic Mail is not secure, may not be read every day, and should not be used for urgent or sensitive issues
