### ISSUE TITLE
Questions about multiple sample analysis

### ISSUE THREAD

**Issue by WangRong423** [welch-lab/MultiVelo#4]
Hi,MultiVelo team,Thank you for giving us such a great tool!
When I try to run my own data, I have some questions.I had 40 samples and performed QC, combined samples, clustering, and correlation analysis between peaks and genes in signac.
Therefore, reading the original data analysis is not a good choice for me. I am wondering whether I can convert my annotated Signac object into loom object when Reading in unspliced and spliced counts, and how the analyzed signac should extract the feature linkage file. Or, if there is another better way to combine samples, you can also tell me, thank you

**Comment by danielee0707** [comment]
Hi Rong, thank you for your interest.

The Seurat team has implemented some functions to convert between popular single-cell objects, including loom and AnnData. See https://satijalab.org/seurat/articles/conversion_vignette.html.

I'm not sure about the output format of Signac's correlation analysis, but you likely have to manually construct an R dataframe that looks like the feature linkage file from 10X. Here is the description https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/output/analysis#fl_output. You probably already have the peak positions, scores (correlations), and distances. Strands can be anything, and significance is ignored. Linkage_type will just be one of the three types.

Since you have 40 samples, I don't know how severe the batch effect is if they came from different libraries, but it can be helpful to check that before running RNA Velocity.

**Comment by WangRong423** [comment]
@danielee0707 Thank you very much for your reply, which is very helpful to me!
 We did run a batch test and found it was negligible. I have checked that the output of Sinac is a GRangs object, but there is only the corresponding relationship between genes and peak, and no peak to peak(this requires an Finding co-accessible networks with Cicero). So, it's ok to take the object I've merged in signac as input, but with some transformation.

GRanges object with 6 ranges and 5 metadata columns:
      seqnames          ranges strand |     score        gene                 peak    zscore      pvalue
         <Rle>       <IRanges>  <Rle> | <numeric> <character>          <character> <numeric>   <numeric>
  [1]     chr1  999867-1000172      * | 0.0746544        HES4  chr1-998613-1001120   6.87498 3.09996e-12
  [2]     chr1 1137017-1137070      * | 0.0571726   LINC01342 chr1-1136000-1138140  10.61043 1.33258e-26
  [3]     chr1 1214138-1217066      * | 0.0521209     TNFRSF4 chr1-1216769-1217362  15.21807 1.34163e-52
  [4]     chr1 1746024-2228695      * | 0.0605889         SKI chr1-1745496-1746551   2.22250 1.31248e-02
  [5]     chr1 1764604-1780457      * | 0.0646326        NADK chr1-1763879-1765328   4.99183 2.99053e-07
  [6]     chr1 1780457-2151206      * | 0.0887444        NADK chr1-2150709-2151702   6.10952 4.99667e-10
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths_

**Comment by WangRong423** [comment]
Hi,danie, I still have questions about sample merging.

I checked the batch effect between the samples and it was not obvious on the RNA, but there were differences on the ATAC.My solution to this problem is to remove another batch of experimental data, which will not affect the purpose of my analysis.

And I don't understand the quality control of RNA loom
sc.pp.filter_cells(adata_rna, min_counts=1000)
sc.pp.filter_cells(adata_rna, max_counts=20000)
Which matrix is filtered, spliced or unspliced, and why?

I gave up the idea of merging samples at the beginning. I am trying to handle each sample separately and merge AnnData objects before running _mv.recover_dynamics_Chrom_. Is this a reasonable approach and how do you think multiple samples should be merged?

**Comment by danielee0707** [comment]
#10
